version: "3.7"

x-defaults:
  db-dsn: &db-dsn postgres://postgres:postgrespassword@postgresql:5432/postgres
  db-host: &db-host postgresql
  db-port: &db-port 5432
  db-username: &db-username postgres
  db-password: &db-password postgrespassword
  db-database: &db-database postgres
  gf-admin-username: &gf-admin-username admin
  gf-admin-password: &gf-admin-password admin
  pga-default-email: &pga-default-email admin@localhost.com
  pga-default-password: &pga-default-password admin


services:
  parser:
    image: parser:development
    restart: always
    build:
      context: ./parser
      dockerfile: Dockerfile
    environment:
      ENV: docker
      TG_BOT_TOKEN: ""
      TG_WEBHOOK_URL: ""
      DB_DRIVER: "postgres"
      DB_HOST: *db-host
      DB_PORT: *db-port
      DB_USERNAME: *db-username
      DB_PASSWORD: *db-password
      DB_DATABASE: *db-database
    ports:
      - 3000:3000
    networks:
      - telebot
    profiles:
      - all
      - parser


  postgresql:
    image: postgres:14.3
    pull_policy: if_not_present
    restart: always
    environment:
      POSTGRES_USER: *db-username
      POSTGRES_PASSWORD: *db-password
      POSTGRES_DB: *db-database
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - telebot
    profiles:
      - all
      - db

  pgadmin:
    depends_on:
      - postgresql
    image: dpage/pgadmin4:6.9
    pull_policy: if_not_present
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: *pga-default-email
      PGADMIN_DEFAULT_PASSWORD: *pga-default-password
    volumes:
      - pga_data:/var/lib/pgadmin
    ports:
      - 5433:80
    networks:
      - telebot
    profiles:
      - all
      - db

  gql:
    depends_on:
      - postgresql
    build:
      context: ./postgraphile
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: *db-dsn
      NODE_ENV: development
    ports:
      - 5000:5000
    networks:
      - telebot
    profiles:
      - all
      - gql

volumes:
  pg_data:
    driver: local
  pga_data:
    driver: local
  # grafana_data:
  #   driver: local
networks:
  telebot: