// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExpensesColumns holds the columns for the "expenses" table.
	ExpensesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "category", Type: field.TypeString},
		{Name: "method", Type: field.TypeString},
		{Name: "owner_name", Type: field.TypeString},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ExpensesTable holds the schema information for the "expenses" table.
	ExpensesTable = &schema.Table{
		Name:       "expenses",
		Columns:    ExpensesColumns,
		PrimaryKey: []*schema.Column{ExpensesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "expense_amount",
				Unique:  false,
				Columns: []*schema.Column{ExpensesColumns[1]},
			},
			{
				Name:    "expense_category",
				Unique:  false,
				Columns: []*schema.Column{ExpensesColumns[2]},
			},
			{
				Name:    "expense_method",
				Unique:  false,
				Columns: []*schema.Column{ExpensesColumns[3]},
			},
			{
				Name:    "expense_owner_name",
				Unique:  false,
				Columns: []*schema.Column{ExpensesColumns[4]},
			},
			{
				Name:    "expense_timestamp",
				Unique:  false,
				Columns: []*schema.Column{ExpensesColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExpensesTable,
	}
)

func init() {
}
