// Code generated by entc, DO NOT EDIT.

package expense

import (
	"time"
)

const (
	// Label holds the string label denoting the expense type in the database.
	Label = "expense"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldOwnerName holds the string denoting the ownername field in the database.
	FieldOwnerName = "owner_name"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the expense in the database.
	Table = "expenses"
)

// Columns holds all SQL columns for expense fields.
var Columns = []string{
	FieldID,
	FieldAmount,
	FieldCategory,
	FieldMethod,
	FieldOwnerName,
	FieldTimestamp,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt time.Time
)
