// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"mickaelalliel.com/telebot/parser/ent/expense"
	"mickaelalliel.com/telebot/parser/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	expenseFields := schema.Expense{}.Fields()
	_ = expenseFields
	// expenseDescCreatedAt is the schema descriptor for createdAt field.
	expenseDescCreatedAt := expenseFields[5].Descriptor()
	// expense.DefaultCreatedAt holds the default value on creation for the createdAt field.
	expense.DefaultCreatedAt = expenseDescCreatedAt.Default.(time.Time)
}
